# Generated by Django 4.0.4 on 2022-04-23 02:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentArchitecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('icon', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='AttachmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('icon', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('md5sum', models.CharField(max_length=32)),
                ('file', models.FileField(upload_to='')),
                ('size', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('tree', models.TextField(default='[]')),
                ('architecture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attachment.attachmentarchitecture')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attachment.attachmenttype')),
            ],
        ),
    ]
