# Generated by Django 4.0.4 on 2022-04-23 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('display_order', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ProductUI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attachment.attachment')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('serials', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('end_of_life_date', models.DateField(blank=True, null=True)),
                ('min_ram', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_hd', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('attachments', models.ManyToManyField(to='attachment.attachment')),
                ('min_cpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='software.productcpu')),
                ('platforms', models.ManyToManyField(blank=True, to='software.productplatform')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='software.product')),
                ('types', models.ManyToManyField(blank=True, to='software.producttype')),
                ('ui', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='software.productui')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='software.vendor')),
            ],
        ),
    ]
